source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['README.md']
keep_files:  ['.git','.svn']
timezone:    America/New_York

future:      true
show_drafts: nil
limit_posts: 0
pygments:    true

domain:      joewiz.org
title:       joewiz.org
author:      Joe Wicentowski
email:       joewiz@gmail.com
description: This is where Joe Wicentowski writes things longer than 140 characters.

feedburner:
  id:        joewiz-org

google_analytics:
  account:   UA-582491-4

github:
  username:  joewiz

twitter:
  username:  joewiz

tumblr:
  username:  joewiz

pinboard:
  username:  joewiz

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true
